//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootstrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spartan
    {
        public int ID { get; set; }
        public string gamertag { get; set; }
        public string company { get; set; }
    }
}
